#!/bin/bash
# SkillClaw Daily Report Generator
exec 2>/dev/null

REPORT="/mnt/gdrive/shared/common/evolved-skills/DAILY-REPORT.md"
EVOLVED="/mnt/gdrive/shared/common/evolved-skills"

echo "# SkillClaw Daily Report — $(date -u '+%Y-%m-%d %H:%M UTC')" > "$REPORT"
echo "" >> "$REPORT"

## Section 1: Evolved Skills
echo "## Evolved Skills" >> "$REPORT"
echo "" >> "$REPORT"
COUNT=0
for skill_dir in $(find "$EVOLVED" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort); do
  skill_name=$(basename "$skill_dir")
  [ "$skill_name" = "DAILY-REPORT.md" ] && continue
  [ ! -f "${skill_dir}/SKILL.md" ] && continue
  title=$(head -1 "${skill_dir}/SKILL.md" | sed 's/^# //')
  desc=$(grep -i "^description:" "${skill_dir}/SKILL.md" | head -1 | sed 's/^description: *//i')
  [ -z "$title" ] && title="(unreadable)"
  echo "### $skill_name" >> "$REPORT"
  echo "- **Title:** $title" >> "$REPORT"
  [ -n "$desc" ] && echo "- **Description:** $desc" >> "$REPORT"
  echo "- **Path:** `$EVOLVED/$skill_name/SKILL.md`" >> "$REPORT"
  echo "" >> "$REPORT"
  COUNT=$((COUNT+1))
done
echo "**Total: $COUNT evolved skills**" >> "$REPORT"
echo "" >> "$REPORT"

## Section 2: Assessment
echo "## Assessment" >> "$REPORT"
echo "" >> "$REPORT"
echo "- **Reviewed:** (mark manually after review)" >> "$REPORT"
echo "- **Approved for deployment:** (mark manually)" >> "$REPORT"
echo "- **Rejected:** (mark manually)" >> "$REPORT"
echo "" >> "$REPORT"

## Section 3: Agent Skills Summary
echo "## Agent Skills (Current)" >> "$REPORT"
echo "" >> "$REPORT"
for agent_dir in $(find /mnt/gdrive/shared/common/agent-skills -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort); do
  agent_name=$(basename "$agent_dir")
  skill_count=$(ls "$agent_dir" 2>/dev/null | wc -l)
  echo "- **$agent_name:** $skill_count skills" >> "$REPORT"
done
echo "" >> "$REPORT"

echo "---" >> "$REPORT"
echo "*Generated by SkillClaw pipeline*" >> "$REPORT"

echo "Report written to $REPORT"
